export const CONSTANTS = {
    INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",
    USER_EXISTS: "USER FOUND",
    USER_CREATED: "USER CREATED",
    NO_USER: "USER NOT FOUND",
    NO_ROUTE: "ROUTE NOT FOUND",
    USER_DATA_FOUND: "USER DATA FOUND",
    USER_DATA_ADDED: "USER DATA ADDED",
    USER_DATA_UPDATED: "USER DATA UPDATED",
    USER_DATA_DELETED: "USER DATA DELETED",
    INCORRECT_CREDENTIALS: "INCORRECT CREDENTIALS",
    ERROR_OCCURED: "ERROR OCCURED",
};
